### ISSUE TITLE
Please Provide Typescript Types

### ISSUE THREAD

**Issue by theprantadutta** [hueindahaus/react-messenger-chat-plugin#2]
Thank you for making this awesome library.  I really didn't do much and I got exactly what I wanted.

## If anyone is trying to use this library with typescript, just create a custom.d.ts in your root and add the following line
```
  declare module 'react-messenger-chat-plugin';
```

**Comment by hueindahaus** [comment]
Hello prantaDutta! Thank you for the feedback! I will definitely add the types for typescript once I am done with my exam period

**Comment by theprantadutta** [comment]
@hueindahaus OKAY

**Comment by hueindahaus** [comment]
Hello, sorry for taking so long, but I've now included types for this package in v.2.0.2 . Please confirm that it works if you are still using it :-) @prantaDutta

**Comment by hueindahaus** [comment]
Closing due to staleness
