### ISSUE TITLE
Import from syxtax in builded package 

### ISSUE THREAD

**Issue by hotrungnhan** [hueindahaus/react-messenger-chat-plugin#3]
Hey [Alexander Huang](https://github.com/hueindahaus) can you plz check on the newest version that still has an import statement after build.
or you can using "type": "module" in package json.

**Comment by hueindahaus** [comment]
Hello @hotrungnhan, sorry for addressing this a bit late, but this should now be resolved in v3.0.4. This version is not backwards compatible so make sure you make the correct adjustments to possible errors. The readme is updated for this!

**Comment by hotrungnhan** [comment]
> 

thanks in advance
