### ISSUE TITLE
NextJS 

### ISSUE THREAD

**Issue by tranngocvan00** [hueindahaus/react-messenger-chat-plugin#4]
it doesn't seem to work with NextJs, how can I use it for NextJS ?

**Comment by phyohtetarkar** [comment]
Please use with nextjs dynamic import outside react component
```
const MessengerChatComponent = dynamic(
  () => import("react-messenger-chat-plugin").then((mcp) => mcp.MessengerChat),
  { ssr: false }
);
```
Then use it

```
{typeof window !== "undefiend" && (
   <MessengerChatComponent
      pageId="<pageId>"
      language="en_US"
      height={24}
      autoExpand={true}
      debugMode={false}
   />
)}
```

**Comment by hueindahaus** [comment]
Hello! Dynamic import is no longer necessary in 3.0.4! 

@tranngocvan00 try updating to latest and see if it fixed it for you. For me, it works in nextjs now.

**Comment by hueindahaus** [comment]
I will reopen this thread if you have further issues, but closing for now
