### ISSUE TITLE
Chat icon not showing

### ISSUE THREAD

**Issue by mlab817** [hueindahaus/react-messenger-chat-plugin#5]
I copy pasted the code in the docs in my app which is created by create-react-app but the messenger button is not showing. I can see the iframe in the dom, however. Am I missing something?

**Comment by idjitjohn** [comment]
same with mine. Any solution?

**Comment by hueindahaus** [comment]
Hello! It is important that you follow every step in the set up. Make sure to use a proxy such as [ngrok](https://ngrok.com/). Facebook does not allow whitelisting of localhost. Whitelist the forwarded URL in your settings on business suite.

**Comment by hueindahaus** [comment]
I also updated the package due to some import issues. Make sure to download the latest version!

**Comment by hueindahaus** [comment]
I'm closing this, but if your problems persist, get back to me on alexanderhuangen@live.se and I will try to resolve your issues :)
